name: Version Increment

on:
  workflow_dispatch:
    inputs:
      auto_version:
        required: true
        default: 'minor'
        description: Choose auto-versioning type
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git config user.email "robertasvi@users.noreply.github.com"
      - run: git config user.name "robertasvi"
      - run: npm version ${{github.event.inputs.auto_version}} -m "v%s"
      - run: VERSION=$(node -p "require('./package.json').version")
      - run: git tag ${VERSION}
      - run: git push --follow-tags
      - run: git push --tags
